import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAward,
  faBuilding,
  faClock,
  faEnvelope,
  faGlobe,
  faGraduationCap,
  faMapMarkerAlt,
  faMobileAlt,
  faPercentage,
  faPhoneSquare,
  faPlusCircle,
  faRunning,
  faSchool,
  faStarHalfAlt,
  faTools,
  faTrashAlt,
  faTrophy,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import {
  faBlackTie,
  faFacebook,
  faGithub,
  faLinkedin,
  faXTwitter,
} from "@fortawesome/free-brands-svg-icons";

library.add(
  faClock,
  faPlusCircle,
  faSchool,
  faTrashAlt,
  faUser,
  faAward,
  faStarHalfAlt,
  faGraduationCap,
  faPercentage,
  faTools,
  faTrophy,
  faBuilding,
  faBlackTie,
  faGlobe,
  faMapMarkerAlt,
  faPhoneSquare,
  faEnvelope,
  faMobileAlt,
  faFacebook,
  faGithub,
  faXTwitter,
  faLinkedin,
  faRunning
);
